---
 - name: create webserver
   hosts: web
   become: yes
   tasks:
     - name: install apache
       yum: 
         name: httpd
         state: present
     - name: started apache
       service:
         name: httpd
         state: started
     - name: install git
       yum:
         name: git
         state: present
