---
 - name: create webserver
   hosts: web
   become: yes
   tasks:
     - name: install apache
       yum: 
         name: httpd
         state: present
       notify:
         - restarted
     - name: started apache
       service:
         name: httpd
         state: started
     - name: install git
       yum:
         name: git
         state: present
     - name: Deploy static website
       copy:
         src: index.html
         dest: /var/www/html/
